import SideBar from "@/components/SideBar"
import { AuthProvider } from "@/context/AuthContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>

      <SideBar children={children} />
    </AuthProvider>

  )
}
